# Site settings
title: Cranston IT
title_p1: Cranston
title_p2: IT
sub_title: Web Development and Consultancy
slogan: Creative Simplicity

favicon: /img/small ITx.png
nav-icon: 

email: info@cranston-it.co.uk
url: http://www.cranston-it.co.uk

description: "Cranston IT are Website Designers, making great responsive websites for individuals and small businesses."
keywords: "Web Developer, Web Consultancy, Website Developer, Website Consultancy, Web Design, Website Design,Creative, Small Businesses, Websites, Responsive, Mobile DevicesGraphic Artist - User Experience Designer"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

menu:
  - title: Portfolio
    url: portfolio
  - title: About
    url: about
  - title: Contact
    url: contact



# Build settings
markdown: kramdown
permalink: pretty
