# Site settings
title: Tim Cranston
title_p1: Tim
title_p2: Cranston
sub_title: Web Development and Consultancy
slogan: Creative Simplicity

favicon: /img/small ITx.png
nav-icon: 

url: https://timcranston.uk

description: "Cranston IT are Website Designers, making great responsive websites for individuals and small businesses."
keywords: "Web Developer, Web Consultancy, Website Developer, Website Consultancy, Web Design, Website Design,Creative, Small Businesses, Websites, Responsive, Mobile DevicesGraphic Artist - User Experience Designer"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

menu:
  - title: About
    url: about
  - title: Portfolio
    url: portfolio



# Build settings
markdown: kramdown
permalink: pretty
